DELETE FROM products;
DELETE FROM sqlite_sequence WHERE name="products";
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Deportivo XXL', 'Ideal para uso diario.', 1058, 177);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo XXL', 'Prenda cómoda y ligera.', 510, 33);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Casual S', 'Diseño moderno y elegante.', 1292, 457);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Casual S', 'Ideal para uso diario.', 1138, 414);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Formal XL', 'Diseño moderno y elegante.', 603, 151);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Deportivo S', 'Prenda cómoda y ligera.', 961, 223);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Deportivo L', 'Diseño moderno y elegante.', 1331, 436);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Casual XXL', 'Prenda cómoda y ligera.', 1286, 441);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Casual L', 'Material de alta calidad.', 889, 187);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Formal XXL', 'Diseño moderno y elegante.', 647, 462);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Deportivo S', 'Material de alta calidad.', 464, 65);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Formal M', 'Material de alta calidad.', 786, 65);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo XL', 'Material de alta calidad.', 762, 454);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Casual L', 'Diseño moderno y elegante.', 430, 193);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo L', 'Prenda cómoda y ligera.', 952, 246);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Formal XL', 'Prenda cómoda y ligera.', 883, 301);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo S', 'Material de alta calidad.', 1128, 348);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo L', 'Prenda cómoda y ligera.', 1224, 39);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Formal L', 'Prenda cómoda y ligera.', 416, 86);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo XXL', 'Diseño moderno y elegante.', 1292, 302);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Formal L', 'Material de alta calidad.', 1017, 334);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo XL', 'Diseño moderno y elegante.', 1288, 350);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Casual S', 'Prenda cómoda y ligera.', 525, 257);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal M', 'Diseño moderno y elegante.', 1386, 34);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo S', 'Perfecta para actividades al aire libre.', 596, 166);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Casual S', 'Material de alta calidad.', 503, 214);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Casual S', 'Ideal para uso diario.', 967, 64);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo XL', 'Perfecta para actividades al aire libre.', 464, 196);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Casual XL', 'Diseño moderno y elegante.', 1465, 282);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Casual M', 'Ideal para uso diario.', 1100, 206);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Casual XXL', 'Prenda cómoda y ligera.', 1006, 322);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo S', 'Perfecta para actividades al aire libre.', 1010, 298);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo M', 'Diseño moderno y elegante.', 1120, 482);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Formal L', 'Ideal para uso diario.', 548, 40);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Deportivo XXL', 'Diseño moderno y elegante.', 783, 264);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo XXL', 'Material de alta calidad.', 1261, 194);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Formal S', 'Ideal para uso diario.', 925, 208);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Formal XXL', 'Material de alta calidad.', 1379, 19);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Casual M', 'Diseño moderno y elegante.', 1338, 340);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Casual M', 'Prenda cómoda y ligera.', 1295, 199);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Deportivo M', 'Material de alta calidad.', 777, 142);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Casual S', 'Diseño moderno y elegante.', 1089, 333);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Formal XXL', 'Perfecta para actividades al aire libre.', 1271, 304);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo S', 'Diseño moderno y elegante.', 424, 443);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo XL', 'Material de alta calidad.', 840, 376);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Formal S', 'Perfecta para actividades al aire libre.', 1090, 121);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Formal XL', 'Ideal para uso diario.', 608, 279);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal XXL', 'Ideal para uso diario.', 548, 480);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo XL', 'Ideal para uso diario.', 1167, 262);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo XL', 'Ideal para uso diario.', 717, 248);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Casual M', 'Diseño moderno y elegante.', 1071, 323);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Casual XXL', 'Material de alta calidad.', 963, 411);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Deportivo XL', 'Diseño moderno y elegante.', 815, 405);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo L', 'Prenda cómoda y ligera.', 805, 41);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Casual L', 'Diseño moderno y elegante.', 551, 111);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Formal XL', 'Perfecta para actividades al aire libre.', 876, 73);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Casual S', 'Diseño moderno y elegante.', 1049, 37);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Casual M', 'Diseño moderno y elegante.', 655, 151);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Deportivo XL', 'Ideal para uso diario.', 1052, 260);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Deportivo M', 'Perfecta para actividades al aire libre.', 960, 405);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Formal XXL', 'Material de alta calidad.', 1055, 297);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Formal S', 'Perfecta para actividades al aire libre.', 1180, 473);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Casual L', 'Prenda cómoda y ligera.', 708, 11);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo M', 'Material de alta calidad.', 874, 374);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Casual L', 'Ideal para uso diario.', 685, 137);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Deportivo XL', 'Perfecta para actividades al aire libre.', 1151, 441);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Deportivo XL', 'Material de alta calidad.', 1331, 17);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Deportivo S', 'Diseño moderno y elegante.', 571, 479);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Deportivo L', 'Ideal para uso diario.', 835, 486);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Casual XL', 'Perfecta para actividades al aire libre.', 1225, 364);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Casual L', 'Ideal para uso diario.', 1070, 320);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Casual L', 'Diseño moderno y elegante.', 1356, 148);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo L', 'Material de alta calidad.', 1283, 252);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Deportivo XL', 'Perfecta para actividades al aire libre.', 913, 28);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Formal S', 'Ideal para uso diario.', 507, 136);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Casual L', 'Perfecta para actividades al aire libre.', 407, 18);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Formal XL', 'Diseño moderno y elegante.', 516, 453);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal M', 'Prenda cómoda y ligera.', 457, 360);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo L', 'Ideal para uso diario.', 445, 103);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo S', 'Prenda cómoda y ligera.', 680, 200);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Casual M', 'Diseño moderno y elegante.', 1008, 319);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Formal M', 'Diseño moderno y elegante.', 720, 337);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Casual XXL', 'Material de alta calidad.', 801, 275);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Casual XXL', 'Perfecta para actividades al aire libre.', 1167, 218);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Casual M', 'Material de alta calidad.', 527, 19);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Casual S', 'Perfecta para actividades al aire libre.', 753, 99);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Casual L', 'Ideal para uso diario.', 1390, 317);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa Casual M', 'Material de alta calidad.', 1438, 253);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal L', 'Perfecta para actividades al aire libre.', 778, 449);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal M', 'Perfecta para actividades al aire libre.', 404, 350);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Deportivo XXL', 'Diseño moderno y elegante.', 463, 98);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Casual S', 'Ideal para uso diario.', 987, 226);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Deportivo L', 'Material de alta calidad.', 599, 100);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón Casual XL', 'Diseño moderno y elegante.', 756, 249);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal XL', 'Perfecta para actividades al aire libre.', 541, 245);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Deportivo L', 'Prenda cómoda y ligera.', 975, 480);
INSERT INTO products (name, description, price, stock) VALUES ('Falda Formal XXL', 'Perfecta para actividades al aire libre.', 973, 51);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera Casual XXL', 'Perfecta para actividades al aire libre.', 1491, 114);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta Formal S', 'Ideal para uso diario.', 1067, 391);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta Deportivo XL', 'Diseño moderno y elegante.', 1117, 347);